export const seedData = {
  projects: [
    {
      name: 'Health of Things',
      image: 'https://i.imgur.com/2MfiTKy.png',
      urlDeploy: '',
      videoDemo:
        'https://www.linkedin.com/in/yamilabraham/details/projects/26059522/multiple-media-viewer/?profileId=ACoAAClbreMBQ9ytIZv7-iZy1iTarFTtf-ikgJo&treasuryMediaId=1635540309438',
      description:
        'I collaborated with a team of 12 data science students. The project consisted of creating an intelligent model capable of detecting anomalies in automotive machines by detecting variables such as vibrations and accelerations in the X, Y, and Z axes and temperatures.',
      tecnologies: [
        'IoT',
        'LoRaWAN',
        'Chirpstack',
        'Mongo',
        'Jupyter Notebook',
        'Numpy',
        'Matplotlib',
        'Python',
        'Pandas',
        'JavaScript',
        'GitHub',
      ],
      types: ['Web'],
      company: 'Webee <> Purdue University',
    },
    {
      name: 'Asset Tracking',
      image:
        'https://i.imgur.com/Kd6NDzb.png',
      urlDeploy: '',
      videoDemo: 'https://www.linkedin.com/in/yamilabraham/details/projects/25869320/multiple-media-viewer/?profileId=ACoAAClbreMBQ9ytIZv7-iZy1iTarFTtf-ikgJo&treasuryMediaId=1635540308604',
      description:
        'I collaborated in a team of 12 data science students. The project consisted of creating an intelligent model capable of locating automotive assets using LoRaWAN and BLE technology.',
      tecnologies: [
        'IoT',
        'Bluetooth',
        'LoRaWAN',
        'Kalman-Filter',
        'Chirpstack',
        'Mongo',
        'Jupyter Notebook',
        'Numpy',
        'Matplotlib',
        'Python',
        'Pandas',
        'JavaScript',
        'GitHub',
      ],
      types: ['Web'],
      company: 'Webee <> Purdue University',
    },
    {
      name: 'Energy Monitoring',
      image:
        'https://i.imgur.com/ISyFq2s.png',
      urlDeploy: '',
      videoDemo:
        'https://www.linkedin.com/in/yamilabraham/details/projects/25312816/multiple-media-viewer/?profileId=ACoAAClbreMBQ9ytIZv7-iZy1iTarFTtf-ikgJo&treasuryMediaId=1635540309416',
      description:
        'Mentoring a team of 12 data science students. The project consisted of creating an intelligent model capable of monitoring energy consumption in manufacturing factories through a database built by collecting measurements from IoT sensors such as voltages, currents, energies, powers, and power factors.',
      tecnologies: [
        'IoT',
        'LoRaWAN',
        'Chirpstack',
        'Mongo',
        'Jupyter Notebook',
        'Numpy',
        'Matplotlib',
        'Python',
        'Pandas',
        'JavaScript',
        'GitHub',
      ],
      types: ['Web'],
      company: 'Webee <> Purdue University',
    },
    {
      name: 'Smart Irrigation',
      image: 'https://i.imgur.com/yJYuvM9.png',
      urlDeploy: '',
      videoDemo: 'https://www.linkedin.com/in/yamilabraham/details/projects/24938047/multiple-media-viewer/?profileId=ACoAAClbreMBQ9ytIZv7-iZy1iTarFTtf-ikgJo&treasuryMediaId=1635540314017',
      description:
        'Mentoring a team of 12 data science students. Based on the first model we went deeper into collecting data from IoT sensors and cross-checked the data with other data sources to optimize the model and predict how much water was needed to irrigate the greenhouses in the next hour.',
      tecnologies: [
        'IoT',
        'LoRaWAN',
        'Chirpstack',
        'Mongo',
        'Jupyter Notebook',
        'Numpy',
        'Matplotlib',
        'Python',
        'Pandas',
        'JavaScript',
        'GitHub',
      ],
      types: ['Web'],
      company: 'Webee <> Purdue University',
    },
    {
      name: 'Piglet Crushing',
      image:
        'https://i.imgur.com/vehISuI.jpg',
      urlDeploy: '',
      videoDemo:'',
      description:
        'Led computer vision project using NVIDIA Jetson Nano development kit to detect crushing events in piglets during the first 3 months of suckling through image recognition processing. The purpose of this development was for a pig producer client as I detected a loss of thousands of dollars per year in the death of piglets.',
      tecnologies: [
        'IoT',
        'LoRaWAN',
        'Chirpstack',
        'Mongo',
        'Jupyter Notebook',
        'NVIDIA Jetson',
        'C++',
        'Python',
        'Docker',
        'Kaggle',
        'JavaScript',
        'GitHub',
      ],
      types: ['Web'],
      company: 'Webee <> Purdue University',
    },
    {
      name: 'VmT1',
      image:
        'https://i.imgur.com/uzfalUs.png',
      urlDeploy: '',
      videoDemo:
        'https://docdro.id/SvzkaLG',
      description:
        '✅ Conoce más sobre 🎚 VmT1. 😷 🤲🏻 Podes medir tu temperatura corporal evitando el contacto fisico y sin tener una persona a dispocisión en el sensado 👨🏻‍💼↔️👩🏼‍💼.',
      tecnologies: [
        'Arduino',
        'Raspberry Pi',
        'Java',
        'C',
        'C++',
        'ESP32',
        'GitHub',
      ],
      types: ['Web'],
      company: 'Volt Motors',
    },
  ],
}
